### ISSUE TITLE
converty pkl files to .fbx data 

### ISSUE THREAD

**Issue by gayatriprasad** [sloganking/FbxToMimic#11]
Hello @SleepingFox88 ! Thank you for the work. I currently have .pkl files with coordinates ( per each frame). Is there any implementation to convert them to .fbx files ? Thank you

**Comment by sloganking** [comment]
I am not familiar with .pkl files or methods for converting them. [BvhToDeepMimic](https://github.com/BartMoyaers/BvhToDeepMimic) is much farther along than this repository. Perhaps you can ask around there.
