### ISSUE TITLE
about 3d to 4d,What is the setting of constants based on?

### ISSUE THREAD

**Issue by kevinWang230** [sloganking/FbxToMimic#9]
for example,fbxBoneName("right shoulder") patch = y-20 How is this '20' value determined?

**Comment by SleepingFox88** [comment]
@kevinWang230 I believe you are referring to these hard coded angle offsets in [JsonToMimic.py](https://github.com/SleepingFox88/FbxToMimic/blob/master/Utils/JsonToMimic.py), under the orange line.
![code](https://i.imgur.com/JLsch2q.png)

Apologies for the disorganization, these are currently manual offsets that I have been experimenting with to see if I could get the model animations translated correctly. The numbers as they are currently are only for testing and were created via trial and error of what seemed to make the Mimic motion animation behave more like the .fbx file animation.

As seen in issue #6 and #5 , .fbx models seem to have some offset to their angles which I have not yet figured out how they are interpreted and work. If anyone can find documentation on how this data is saved in .fbx files, it would be quite helpful.
